config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources 'home', only: [:index] do
    collection do
      get 'clusterer'
      get 'bubble'
      get 'network'
    end
  end

end

app/models/location_map.rb
class LocationMap < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @heat_maps = LocationMap.all
  end

  def clusterer
    @clusters = LocationMap.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gmaps/cluster_map_marker.rb
module Gmaps
  class ClusterMapMarker
    def initialize(cluster)
      raise ArgumentError if !cluster.is_a? LocationMap
      @cluster = cluster
    end

    def build(description)
      {
        lat:         @cluster.latitude,
        lng:         @cluster.longitude,
        description: description
      }
    end
  end
end

app/helpers/gmaps/heatmap_marker.rb
module Gmaps
  class HeatmapMarker
    def initialize(heatmap)
      raise ArgumentError if !heatmap.is_a? LocationMap
      @heatmap = heatmap
    end

    def build(description)
      {
        lat:         @heatmap.latitude,
        lng:         @heatmap.longitude,
        description: description
      }
    end
  end
end

app/helpers/gmaps_helper.rb
module GmapsHelper
  def heatmap_description(heatmap)
    render(partial: 'home/heatmap/marker', locals: {heatmap: heatmap})
  end

  def cluster_map_description(heatmap)
    render(partial: 'home/cluster_map/marker', locals: {cluster_map: cluster_map})
  end

  def build_markers(list)
    markers = list.inject([]) do |markers, item|
      case item
        when LocationMap then markers << Gmaps::HeatmapMarker.new(item).build(heatmap_description(item))
        when LocationMap then markers << Gmaps::ClusterMapMarker.new(item).build(cluster_map_description(item))
      end
    end
    markers.to_json if markers.present?
  end

  def render_heat_map_with_markers(markers, center_lat: 37.775, center_lng: -122.434, zoom: 12)
    render partial: 'maps/heat_map', locals: { markers: build_markers(markers), center_lat: center_lat, center_lng: center_lng, zoom: zoom }
  end

  def render_cluster_map_with_markers(markers, center_lat: 37.775, center_lng: -122.434, zoom: 12)
    render partial: 'maps/cluster_map', locals: { markers: build_markers(markers), center_lat: center_lat, center_lng: center_lng, zoom: zoom }
  end
end

app/views/home/bubble.html.slim
#home-bubble-container
  #bubble-map
  .link-to
    p = link_to 'cluster', clusterer_home_index_path
    p = link_to 'heatmap', home_index_path
    p = link_to 'network', network_home_index_path


javascript:

app/views/home/cluster_map/_marker.html.slim
.home-cluster-map-marker-container.marker-popup
  h4.marker-popup-title = cluster_map.name
  label Address:
  p #{cluster_map.name} #{cluster_map.latitude} #{cluster_map.longitude}

app/views/home/clusterer.html.slim
#home-clusterer-container
  #map
    = render_cluster_map_with_markers(@clusters)
  .link-to
    p = link_to 'heatmap', home_index_path
    p = link_to 'bubble', bubble_home_index_path
    p = link_to 'network', network_home_index_path

app/views/home/heatmap/_marker.html.slim
.home-heat-map-marker-container.marker-popup
  h4.marker-popup-title = heatmap.name
  label Address:
  p #{heatmap.name} #{heatmap.latitude} #{heatmap.longitude}

app/views/home/index.html.slim
#home-index-container
  .map
    = render_heat_map_with_markers(@heat_maps)
  .link-to
    p = link_to 'cluster', clusterer_home_index_path
    p = link_to 'bubble', bubble_home_index_path
    p = link_to 'network', network_home_index_path

app/views/home/network.html.slim
#home-network-container
  #network-map
  .link-to
    p = link_to 'cluster', clusterer_home_index_path
    p = link_to 'heatmap', home_index_path
    p = link_to 'bubble', bubble_home_index_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Map
    script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAEl2cTGRKtqxxsS0XnNP8LWd9mxn2Ej-k&libraries=visualization"
    script src="/assets/cluster_data.json"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = yield

app/views/maps/_cluster_map.html.slim
- markers = '[]' if markers.nil?

.maps-heat-map-container
  #cluster-map

  javascript:
    function initClusterMap() {
      
    }

    initClusterMap();

app/views/maps/_heat_map.html.slim
- markers = '[]' if markers.nil?

.maps-heat-map-container
  #heat-map

  javascript:
    var map, cluster_map;

    function initHeatMap() {
      map = new google.maps.Map(document.getElementById('heat-map'), {
        zoom: 13,
        center: new google.maps.LatLng(#{center_lat}, #{center_lng}),
        mapTypeId: google.maps.MapTypeId.SATELLITE
      });

      heatmap = new google.maps.visualization.HeatmapLayer({
        data: getPoints(#{markers.html_safe}),
        map: map
      });
    }

    function getPoints(markers) {
      arr = [];

      $.each(markers, function(index, location){
        arr.push(new google.maps.LatLng(location.lat, location.lng));
      });

      return arr
    }

    function toggleHeatmap() {
      heatmap.setMap(heatmap.getMap() ? null : map);
    }

    function changeGradient() {
      var gradient = [
        'rgba(0, 255, 255, 0)',
        'rgba(0, 255, 255, 1)',
        'rgba(0, 191, 255, 1)',
        'rgba(0, 127, 255, 1)',
        'rgba(0, 63, 255, 1)',
        'rgba(0, 0, 255, 1)',
        'rgba(0, 0, 223, 1)',
        'rgba(0, 0, 191, 1)',
        'rgba(0, 0, 159, 1)',
        'rgba(0, 0, 127, 1)',
        'rgba(63, 0, 91, 1)',
        'rgba(127, 0, 63, 1)',
        'rgba(191, 0, 31, 1)',
        'rgba(255, 0, 0, 1)'
      ]
      heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
    }

    function changeRadius() {
      heatmap.set('radius', heatmap.get('radius') ? null : 20);
    }

    function changeOpacity() {
      heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
    }

    // Heatmap data: 500 Points
    initHeatMap();